// jokes-vue/src/App.vue
<template>
  <div class="app">
    <h1>Joke Collection</h1>
    
    <JokeList
      :jokes="jokes"
      :current-page="currentPage"
      :total-pages="totalPages"
      @page-change="loadPage"
      @joke-deleted="handleJokeDeleted"
      @joke-rated="handleJokeRated"
    />
    
    <button class="add-joke-btn" @click="showAddModal = true">
      Add New Joke
    </button>
    
    <AddJokeModal
      v-model="showAddModal"
      @joke-added="handleJokeAdded"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import type { Joke } from './types/joke';
import { jokeService } from './services/jokeService';
import JokeList from './components/JokeList.vue';
import AddJokeModal from './components/AddJokeModal.vue';

const jokes = ref<Joke[]>([]);
const currentPage = ref(1);
const totalPages = ref(1);
const showAddModal = ref(false);

async function loadJokes() {
  const { jokes: _jokes, totalPages: _totalPages } = await jokeService.getJokes(currentPage.value, 20);
  jokes.value = _jokes;
  totalPages.value = _totalPages;
}

async function loadPage(page: number) {
  currentPage.value = page;
  await loadJokes();
}

function handleJokeDeleted(id: number) {
  jokes.value = jokes.value.filter(joke => joke._id !== id);
  loadJokes();
}

function handleJokeRated(updatedJoke: Joke) {
  const index = jokes.value.findIndex(joke => joke._id === updatedJoke._id);
  if (index !== -1) {
    jokes.value[index] = { ...jokes.value[index], ...updatedJoke };
  }
}

function handleJokeAdded() {
  loadJokes();
}

onMounted(() => {
  loadJokes();
});
</script>

<style>
.app {
  max-width: 1200px;
  margin: 0 auto;
}

.add-joke-btn {
  position: fixed;
  bottom: 2rem;
  right: 2rem;
  background: #4CAF50;
  color: white;
  border: none;
  padding: 1rem 2rem;
  border-radius: 50px;
  cursor: pointer;
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
}

h1 {
  text-align: center;
  margin-bottom: 2rem;
}
</style>

// jokes-react/src/App.tsx
import { useState, useEffect } from 'react'
import { JokeList } from './components/JokeList'
import { AddJokeModal } from './components/AddJokeModal'
import { jokeService } from './services/jokeService'
import type { Joke } from './types/joke'
import './App.css'

function App() {
  const [jokes, setJokes] = useState<Joke[]>([])
  const [currentPage, setCurrentPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const [showAddModal, setShowAddModal] = useState(false)

  const loadJokes = async () => {
    const { jokes: _jokes, totalPages: _totalPages } = await jokeService.getJokes(currentPage, 20)
    setJokes(_jokes)
    setTotalPages(_totalPages)
  }

  const handlePageChange = async (page: number) => {
    setCurrentPage(page)
    await loadJokes()
  }

  const handleJokeDeleted = (id: number) => {
    setJokes(jokes => jokes.filter(joke => joke._id !== id))
    loadJokes()
  }

  const handleJokeRated = (updatedJoke: Joke) => {
    setJokes(jokes => jokes.map(joke => 
      joke._id === updatedJoke._id ? { ...joke, ...updatedJoke } : joke
    ))
  }

  const handleJokeAdded = () => {
    loadJokes()
  }

  useEffect(() => {
    loadJokes()
  }, [currentPage])

  return (
    <div className="app">
      <h1>Joke Collection</h1>
      
      <JokeList
        jokes={jokes}
        currentPage={currentPage}
        totalPages={totalPages}
        onPageChange={handlePageChange}
        onJokeDeleted={handleJokeDeleted}
        onJokeRated={handleJokeRated}
      />
      
      <button className="add-joke-btn" onClick={() => setShowAddModal(true)}>
        Add New Joke
      </button>
      
      <AddJokeModal
        show={showAddModal}
        onClose={() => setShowAddModal(false)}
        onJokeAdded={handleJokeAdded}
      />
    </div>
  )
}

export default App
